### ISSUE TITLE
NotImplementedError() raised

### ISSUE THREAD

**Issue by joshkersey** [mathiasertl/django-hashers-passlib#1]
Receiving this error after adding `'hashers_passlib.phpass'` to `PASSWORD_HASHERS` in Django 1.6.2 settings. Looking at the `BasePasswordHasher` class in Django I see this documentation:

``` python
When creating your own hasher, you need to override algorithm,
verify(), encode() and safe_summary().
```

It appears that django-hashers-passlib is missing the required `safe_summary()` method when overriding the `BasePasswordHasher` class.

I hastily added a `safe_summary()` method to `PasslibHasher` that I pulled out of `django.contrib.auth.hashers` that works for PHPass so that I could move past this roadblock for the time being. Obviously this won't work for all hashes:

``` python
def safe_summary(self, encoded):
        from django.contrib.auth.hashers import mask_hash, _, SortedDict
        algorithm, salt, hash = encoded.split('$', 2)
        assert algorithm == self.algorithm
        return SortedDict([
            (_('algorithm'), algorithm),
            #(_('salt'), mask_hash(salt, show=2)),
            (_('hash'), mask_hash(hash)),
        ])
```

**Comment by mathiasertl** [comment]
Thanks for your report. I've just released version 0.2 adding (among a few other minor changes) a generic safe_summary method for all hashers.

The django admin interface now works with a phpass hash. Let me know if you have any problems!
