### ISSUE TITLE
How to use bcrypt in Django without bycrypt$ prefix?

### ISSUE THREAD

**Issue by JanMalte** [mathiasertl/django-hashers-passlib#2]
How can I use the provided converter to use bcrypted passwords without having a `bcrypt$` prefix for all password hashes?

Using the converter `'hashers_passlib.converters.bcrypt'` as `PASSWORD_HASHERS` is not working. `django.contrib.auth.hashers.BCryptPasswordHasher` is working if the passwords are having the `bcrypt$` prefix.

**Comment by mathiasertl** [comment]
Apologies for the late reply, I must have overlooked this ticket. I hope my answer is still relevant.

Djangos password hashing system depends on every hash having a prefix like `bcrypt$` identifying the hash algorithm used. You cannot have hashes without such a prefix in the database. 

The converters (see relevant chapter in the README!) are not intended to be used in `PASSWORD_HASHERS` but to convert stock bcrypt hashes to hashes usable by Django and back. In case of bcrypt, nothing really happens but the adding the `bcrypt$` prefix (or stripping it, when converting back). So you can use the converter to produce usable hashes for Django and then use Djangos stock `BCryptPasswordHasher`.
