### ISSUE TITLE
Cannot import name SortedDict while trying to log into the admin panel

### ISSUE THREAD

**Issue by stackOverflower92** [mathiasertl/django-hashers-passlib#5]
I had the summary problem (which I solved upgrading to 0.2) but now I have this one while logging into admin panel.
`
Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/login/?next=/admin/
1.11.2
ImportError
cannot import name SortedDict
E:\stack_overflower\Documents\Dev\SDKs\python\python27\lib\site-packages\hashers_passlib\__init__.py in <module>, line 23
E:\stack_overflower\Documents\Dev\SDKs\python\python27\python.exe
2.7.10
['E:\\stack_overflower\\Documents\\Dev\\Repos\\BitBucket\\CrossFitSassuolo',  'e:\\stack_overflower\\documents\\dev\\sdks\\python\\python27\\scripts\\src\\django-mailer',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\django_spirit-0.5.0.dev0-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\pytz-2017.2-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\unicode_slugify-0.1.4-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\django_djconfig-0.5.3-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\django_infinite_scroll_pagination-0.2.0-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\mistune-0.7.1-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\whoosh-2.7.0-py2.7.egg',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages\\unidecode-0.4.20-py2.7.egg',  'C:\\WINDOWS\\SYSTEM32\\python27.zip',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\DLLs',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\plat-win',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\lib-tk',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27',  'E:\\stack_overflower\\Documents\\Dev\\SDKs\\python\\python27\\lib\\site-packages']
Mar, 19 Set 2017 00:51:31 +0200
`

**Comment by mathiasertl** [comment]
It appears you are using version 0.2 of this library. The line in question is no longer present in 0.3.
